showProgress;29
parseProgressSteps5%;39
parseProgressSteps10%;37
collectProgressSteps2%;37
collectProgressSteps5%;35
collectProgressSteps10%;33
filterProgressSteps2%;33
filterProgressSteps5%;31
filterProgressSteps10%;29
